<h2>Login Page</h2>
<!-- frontend for login -->
<?php echo $this->tag->form("login/login"); ?>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField(["email", "value" => $this->cookies->get('email'), "required" => true]); ?>
</p>
<p>
    <label for="email">Password</label>
    <?php echo $this->tag->passwordField([
        "password",
        "value" => $this->cookies->get('password'), "required" => true
    ]); ?>
</p>
<p>
    <?php echo $this->tag->submitButton(["Login", "class" => "btn-success"]); ?>
</p>

</form>