<!-- frontend for signing up th user -->
<h2>Sign up using this form</h2>
<?php echo $this->tag->form("signup/register"); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField(["name", "required" => true]); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField(["email", "required" => true]); ?>
</p>
<p>
    <label for="email">Password</label>
    <?php echo $this->tag->textField(["password", "required" => true]); ?>
</p>

<p>
    <label for="check">Remember Me</label>
    <?php echo $this->tag->checkField("check"); ?>
</p>
<p>
    <?php echo $this->tag->submitButton(["Register", "class" => "btn-success"]); ?>
</p>

</form>